### ISSUE TITLE
Add tests for expanded `getblockstats`

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/bitcoin#4]
https://github.com/bitcoinops/bitcoin/tree/expand-getblockstats added new statistics to the `getblockstats` RPC method, but didn't include functional tests. It'd be good to have tests so we can occasionally rebase the branch on master (eg https://github.com/bitcoinops/bitcoin/pulls) and have confidence that we're not breaking anything.

It should be fairly straightforward to update https://github.com/bitcoinops/bitcoin/blob/8968f345d4303e2a4eabcb3f33a7c9e7ddc35b59/test/functional/rpc_getblockstats.py to test the new statistics.

**Comment by jnewbery** [comment]
@0xB10C @bitschmidty : let me know if either of you are interested in taking this on.

**Comment by 0xB10C** [comment]
I'll probably pick this up in the next days assuming no one has started working on it yet. Good way for me to learn more about the functional test framework.

**Comment by bitschmidty** [comment]
@0xB10C Ive started on this today as a way to get familiar with both getblockstats and the functional tests as well.  But dont let my starting hold you back!

**Comment by jnewbery** [comment]
I recommend you get together before @0xB10C replicates any work that @bitschmidty has done already.

**Comment by 0xB10C** [comment]
Tests added in #5.
